### PR TITLE
Fix kernel include new path in protected.c

### PR DESCRIPTION
**Pull request by psxdev**

### CODE REVIEW

**Comment by hitodama** [comment]
First of all thank you for the first pull request ^^!

I have a question for you here:

I did not want to move the headers to /sce because sony does not use /sce from what I have seen. It's just /include/kernel.h. But /include became messy with this mix (esp if we wanna hand-maintain it), so what I did is move it to /sce but I include /sce regularly as -I /include/sce. What do you think would be best? I think it would also work to move all headers to /include/libc_internal/ but then I would need to -I /include/libc_internal to get string.h ...

Ideas? Just include sce/... and not be sony compatible?

**Comment by psxdev** [comment]
i like more kernel.h without sce 

 include reveresed sce headers on /include/sce can be more easy to manage/maintain but as you say we would need to add default include/sce to compiler flags. So my vote is put all sony future reversed includes per module in sce directory but maintaining compatibility with names with sony with -I /include/sce flag

**Comment by hitodama** [comment]
So you agree with what I did and how I did it? (nice to hear ^^)
Sad that there is no optimal way :) Close the pull request?

**Comment by psxdev** [comment]
yes close it.

**Comment by hitodama** [comment]
Thanks for the input! I appreciate the involvement in the design decisions and the thoughts :) Please open issues and pull requests (or mail) if you got any other improvement ideas.

**Pull request closed without merging**
